#! /bin/python

from lxml import etree
from lxml.etree import tostring
import sys
import os
import re
import json
import httplib2

# get the CLI args
args = [];
args = list(sys.argv);

shell = args.pop(0);      # pop the shell command name

for checkhelp in args:
  if checkhelp == "--help" or checkhelp == "-h":
    print "Usage: ordered2procedure [id1] [id2] [id3]...";
    exit ();

if len(args) < 1:
  print "Usage: ordered2procedure [id1] [id2] [id3]...";
  exit ();

h = httplib2.Http(disable_ssl_certificate_validation=True);

# Get the TopicID from each arg and use it to perform the search and replace
for topicid in args:
  resp, content = h.request('https://skynet.usersys.redhat.com:8443/pressgang-ccms/rest/1/topic/get/json/'+topicid+'/', method="GET");
  if resp['status'] == '200':
    os.system('clear')
    topic = json.loads(content)
    doc = etree.fromstring(topic['xml'])
    foundol = False
    for element in doc:
      if element.tag == "orderedlist":
        foundol = True
        print "Note: orderedlist found in topic "+topicid
        print tostring(element, pretty_print = True)
        userinput = raw_input('Convert to procedure (Y/n): ')
        if not userinput:
          userinput = "Y"
        if userinput.upper() == "Y":
          print "Changing to procedure and saving back to Pressgang"
          element.tag = "procedure"
          for subelement in element:
            if subelement.tag == "listitem":
              subelement.tag = "step"
#          os.system('clear')
#          print tostring(doc, pretty_print = True)
          topic['xml'] = tostring(doc)
          topic['configuredParameters'] = [ 'xml']
          result = json.dumps(topic, sort_keys=True, indent=2)
#          result = json.dumps(topic, indent=2)
          putresp, putcontent = h.request('https://skynet.usersys.redhat.com:8443/pressgang-ccms/rest/1/topic/update/json/', method="POST", body=result, headers={'content-type':'application/json'});
          if putresp['status'] == '200':
            message = "Saved";
          else:
            message = "Error "+putresp['status'];
          print "Topic "+topicid+": "+message;
    if foundol is False:
      print "Note: orderedlist not found in topic "+topicid
  else:
    print "Fail!"