#! /bin/python

import json
import httplib2
import re
import sys

def parsespec (specfile):
  id_list = []
  spec = open(specfile, 'r').readlines()
  while not (spec[0].startswith('Chapter') | spec[0].startswith('Section') | spec[0].startswith('Part') | spec[0].startswith('Appendix') ):
    # print "Removing: " + spec[0]
    spec.pop(0)
  for line in spec:
    if not line.lstrip(' ').startswith('#') and re.search("[\[\]]", line):
      output = re.search(r"\[(.+)\]", line)
      id_list.append(output.group(1).split(',')[0])
  return id_list

# get the CLI args
args = [];
args = list(sys.argv);

shell = args.pop(0);      # pop the shell command name

if not args:
  args = {'--help'};

for checkhelp in args:
  if checkhelp == "--help" or checkhelp == "-h":
    print "Usage: skynet-search-replace [searchterm] [replaceterm] [id1] [id2] [id3]...";
    exit ();

if len(args) < 3:
  print "Usage: skynet-search-replace [searchterm] [replaceterm] [id1] [id2] [id3]...";
  exit ();
else:
  term = args.pop(0)          # set the search term/regex
  replaceterm = args.pop(0)   # set the replacement term
  specfile = args.pop(0)      # set the cspec file

id_list = parsespec (specfile);

print "Replacing \"" + term + "\" with \"" + replaceterm + "\" in " + specfile

# Pfft, we don't need SSL validation!
h = httplib2.Http(disable_ssl_certificate_validation=True);

# Get the TopicID from each arg and use it to perform the search and replace
for topicid in id_list:
  resp, content = h.request('https://skynet.usersys.redhat.com:8443/pressgang-ccms/rest/1/topic/get/json/'+topicid+'/', method="GET");
  if resp['status'] == '200':
    obj = json.loads(content);
    if obj['xml'].find(term) > 0:
      obj['xml'] = obj['xml'].replace(term, replaceterm)
      obj['title'] = obj['title'].replace(term, replaceterm)
      # print obj['xml']
      sendobj = {'id': obj['id'], 'title': obj['title'], 'xml': obj['xml'], 'configuredParameters': [ 'xml', 'title']};
      result = json.dumps(sendobj, indent=2);
      putresp, putcontent = h.request('https://skynet.usersys.redhat.com:8443/pressgang-ccms/rest/1/topic/update/json/', method="POST", body=result, headers={'content-type':'application/json'});
      if putresp['status'] == '200':
        message = "Replaced (Term \"" + term + "\" with \"" + replaceterm + "\")";
      else:
        message = "Error "+putresp['status'];
    else:
      message = "Skipped (Term \"" + term + "\" not found)"
    print "Topic "+topicid+": "+message;
  else:
    print "Error: Invalid topic ID or faulty connection to SkyNet";
    exit ();
