#! /bin/python

from lxml import etree
from lxml.etree import tostring
from xml.sax.saxutils import escape
import sys
import os
import re
import json
import httplib2

# get the CLI args
args = [];
args = list(sys.argv);

shell = args.pop(0);      # pop the shell command name

if not args:
  args = {'--help'};

for checkhelp in args:
  if checkhelp == "--help" or checkhelp == "-h":
    print "Usage: topic-push [id1] [id2] [id3]...";
    exit ();

if len(args) < 1:
  print "Usage: topic-push [id1] [id2] [id3]...";
  exit ();


# Pfft, we don't need SSL validation!
h = httplib2.Http(disable_ssl_certificate_validation=True);

# Get the TopicID from each arg and use it to perform the search and replace
for file in args:
  content = open(file, "r")
  topicxml = etree.fromstring(content.read())
  title = topicxml.find("title")
  etree.strip_tags(title, '*')
  title = title.text
  sendobj = {'title': title, 'description': title, 'xml': content.read(), 'locale': 'en-US', 'configuredParameters': [ 'title','description','xml','locale']};
  result = json.dumps(sendobj, indent=2)
  resp, content = h.request('http://skynet.usersys.redhat.com:8080/pressgang-ccms/rest/1/topic/create/json?message=Initial+Topic+Creation&flag=2&userId=89', method="POST", body=result, headers={'Content-Type':'application/json'})
  if resp['status'] == '200':
    topicid = json.loads(content)['id']
    print title+" ["+str(topicid)+"]"
  else:
    print "Error: Bad Connection to Pressgang CCMS (Error code: " + resp['status'] + ")"
    exit ()
