#! /bin/python

import json
import httplib2
import re
import sys

# get the CLI args
args = [];
args = list(sys.argv);

shell = args.pop(0);      # pop the shell command name

if not args:
  args = {'--help'};

for checkhelp in args:
  if checkhelp == "--help" or checkhelp == "-h":
    print "Usage: topic-grab [id1] [id2] [id3]...";
    exit ();

if len(args) < 1:
  print "Usage: topic-grab [id1] [id2] [id3]...";
  exit ();


# Pfft, we don't need SSL validation!
h = httplib2.Http(disable_ssl_certificate_validation=True);

# Get the TopicID from each arg and use it to perform the search and replace
for topicid in args:
  resp, content = h.request('https://skynet.usersys.redhat.com:8443/pressgang-ccms/rest/1/topic/get/json/'+topicid+'/', method="GET");
  if resp['status'] == '200':
    obj = json.loads(content);
    print "Writing topic "+topicid+" to file "
    text_file = open(topicid+".txt", "w")
    text_file.write(obj['xml'])
    text_file.close()
  else:
    print "Error: Invalid topic ID or faulty connection to SkyNet";
    exit ();


